Server : 
    port : 9091
spring:
    application:
        name: StudentAssignment-Service
        
eureka:
    clinet:
        register-with-eureka : true
        fetch-registry : true
        service - url:
            defaultZone: http://localhost:8761/eureka/
    instance : 
        hotsname: localhost

